# Generated by Django 3.2.13 on 2022-12-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('report', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('spam', 'Unwanted commercial content or spam'), ('pornography', 'Pornography or sexually explicit material'), ('child_abuse', 'Child abuse'), ('hate_speech', 'Hate speech or graphic violence'), ('terrorism', 'Promotes terrorism'), ('bullying', 'Harassment or bullying'), ('suicide', 'Suicide or self injury'), ('misinformation', 'Misinformation')], max_length=255)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
