# Generated by Django 3.2.13 on 2022-12-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20221219_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_date', models.DateTimeField(auto_now_add=True)),
                ('block_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocker_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'block_user')},
            },
        ),
    ]
