"""
Django settings for raisin project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from .settings_common import BASE_DIR, SITE_URL

ANDROID_CHANNEL_ID = os.getenv("RAISIN_ANDROID_CHANNEL_ID")
ANDROID_APP_ID = os.getenv("RAISIN_ANDROID_APP_ID")
ANDROID_CLIENT_ID = os.getenv("RAISIN_ANDROID_CLIENT_ID")
ANDROID_CALLBACK_SECRET_KEY = 'z4sn1EdzialYR0b0T'
ANDROID_GOOGLE_SECRET_KEY = os.getenv("RAISIN_ANDROID_GOOGLE_SECRET_KEY")
ANDROID_CODE_PATH = os.path.join(BASE_DIR, 'data', 'android-code.txt')
ANDROID_REFRESH_TOKEN_PATH = os.path.join(
    BASE_DIR, 'data', 'android-refresh-token.txt'
)
ANDROID_REDIRECT_URI = SITE_URL + "/api/donations/android/callback?raisin_token=z4sn1EdzialYR0b0T"  # noqa

ANDR_AUTH_TMP = (
    "https://accounts.google.com/o/oauth2/auth?scope=https://"
    "www.googleapis.com/auth/androidpublisher&response_type=code"
    "&access_type=offline&redirect_uri=%(redirect_uri)s"
    "&client_id=%(client_id)s"
)

ANDROID_WEB_AUTH_URL = ANDR_AUTH_TMP % {
    'client_id': ANDROID_CLIENT_ID,
    'redirect_uri': ANDROID_REDIRECT_URI
}
