"""
Django settings for raisin project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

LOGFILE_PATH_DIR = os.getenv("RAISIN_LOGFILE_PATH_DIR")
LOGFILE_PATH = os.path.join(LOGFILE_PATH_DIR, "logs.log")
LOGFILE_PATH_SQL = os.path.join(LOGFILE_PATH_DIR, "sql-log.log")
LOGFILE_PATH_PUSH_NOTIFY = os.path.join(LOGFILE_PATH_DIR, "push-notify.log")
LOGFILE_PATH_COMMAND = os.path.join(LOGFILE_PATH_DIR, "command.log")
LOGFILE_PATH_COMMAND_STAR_REVIEWS = os.path.join(
    LOGFILE_PATH_DIR, "command-sr.log"
)
LOGFILE_PATH_COMMAND_KEYWORDS = os.path.join(
    LOGFILE_PATH_DIR, "command-relevancy-keywords.log"
)
LOGFILE_PATH_ADD_WP = os.path.join(LOGFILE_PATH_DIR, "add-wp-log.log")
LOGFILE_PATH_APP_IOS_CHECK = os.path.join(
    LOGFILE_PATH_DIR, "app-ios-check.log"
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '[%(levelname)s %(module)s @ %(asctime)s] %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOGFILE_PATH,
            'formatter': 'verbose',
        },
        'pushnotifyfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_PUSH_NOTIFY,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'commandfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_COMMAND,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'add_wp_log_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_ADD_WP,
            # # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'command_star_reviews_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_COMMAND_STAR_REVIEWS,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'command_keywords_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_COMMAND_KEYWORDS,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'sql_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_SQL,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'app_ios_check_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOGFILE_PATH_APP_IOS_CHECK,
            # 'maxBytes': 1024 * 1024 * 4,  # 4 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        '': {
            # 'handlers': ['file', 'console'],
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            # 'handlers': ['null'],
            # 'handlers': ['file', 'console'],
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db.backends': {
            # 'handlers': ['null'],
            # 'handlers': ['file', 'console'],
            'handlers': ['sql_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'web': {
            # 'handlers': ['file', 'console'],
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'pushnotify': {
            # 'handlers': ['file', 'console'],
            'handlers': ['pushnotifyfile', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'command': {
            # 'handlers': ['file', 'console'],
            'handlers': ['commandfile', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'command_star_reviews': {
            # 'handlers': ['file', 'console'],
            'handlers': ['command_star_reviews_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'command_keywords': {
            # 'handlers': ['file', 'console'],
            'handlers': ['command_keywords_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'add_wp_log': {
            # 'handlers': ['file', 'console'],
            'handlers': ['add_wp_log_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'app_ios_check': {
            # 'handlers': ['file', 'console'],
            'handlers': ['app_ios_check_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
