# Generated by Django 2.2.28 on 2022-07-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from web.utils.default_data import get_erased_user_uid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0052_auto_20220714_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title EN')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title FR')),
                ('title_ja', models.CharField(blank=True, max_length=200, verbose_name='title JA')),
                ('title_it', models.CharField(blank=True, max_length=200, verbose_name='title IT')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='title ES')),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_fr', models.TextField(blank=True)),
                ('meta_description_ja', models.TextField(blank=True)),
                ('meta_description_it', models.TextField(blank=True)),
                ('meta_description_es', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_fr', models.TextField(blank=True)),
                ('content_ja', models.TextField(blank=True)),
                ('content_it', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('status_en', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_fr', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_ja', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_it', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_es', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('comment_number', models.IntegerField(default=0)),
                ('likevote_number', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='news_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.AbstractImage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='News')),
            ],
            options={
                'db_table': 'news_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.NewsImage'),
        ),
        migrations.AddField(
            model_name='news',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
