# Generated by Django 2.2.28 on 2022-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220715_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvenue',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
