# Generated by Django 2.2.28 on 2022-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220715_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvenue',
            name='is_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='is_wine_shop',
            field=models.BooleanField(default=False),
        ),
    ]
