# Generated by Django 3.2.13 on 2022-08-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_featuredvenue_connected_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredvenue',
            name='is_bar',
        ),
        migrations.RemoveField(
            model_name='featuredvenue',
            name='is_restaurant',
        ),
        migrations.RemoveField(
            model_name='featuredvenue',
            name='is_wine_shop',
        ),
    ]
