# Generated by Django 3.2.13 on 2022-09-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_abstractimage_real_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_auto_20220822_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title EN')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title FR')),
                ('title_ja', models.CharField(blank=True, max_length=200, verbose_name='title JA')),
                ('title_it', models.CharField(blank=True, max_length=200, verbose_name='title IT')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='title ES')),
                ('page_code', models.CharField(max_length=200)),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_fr', models.TextField(blank=True)),
                ('meta_description_ja', models.TextField(blank=True)),
                ('meta_description_it', models.TextField(blank=True)),
                ('meta_description_es', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_fr', models.TextField(blank=True)),
                ('content_ja', models.TextField(blank=True)),
                ('content_it', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('status_en', models.CharField(blank=True, default=10, max_length=200, verbose_name='status ES')),
                ('status_fr', models.CharField(blank=True, default=10, max_length=200, verbose_name='status ES')),
                ('status_ja', models.CharField(blank=True, default=10, max_length=200, verbose_name='status ES')),
                ('status_it', models.CharField(blank=True, default=10, max_length=200, verbose_name='status ES')),
                ('status_es', models.CharField(blank=True, default=10, max_length=200, verbose_name='status ES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=models.SET('f3cd478f-6e98-4dd8-a5bd-d5d286892b3e'), related_name='website_page_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsitePageImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.abstractimage')),
                ('website_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.websitepage')),
            ],
            options={
                'db_table': 'website_page_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.websitepageimage'),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_page_last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
