# Generated by Django 3.2.13 on 2022-11-18 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0062_auto_20220916_0720'),
        ('news', '0010_auto_20221104_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quote', models.CharField(blank=True, max_length=200, verbose_name='default quote')),
                ('quote_en', models.TextField(blank=True)),
                ('quote_fr', models.TextField(blank=True)),
                ('quote_ja', models.TextField(blank=True)),
                ('quote_it', models.TextField(blank=True)),
                ('quote_es', models.TextField(blank=True)),
                ('status_en', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_fr', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_ja', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_it', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_es', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=models.SET('f3cd478f-6e98-4dd8-a5bd-d5d286892b3e'), related_name='quote_author', to=settings.AUTH_USER_MODEL)),
                ('connected_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.place')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.abstractimage')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.quote')),
            ],
            options={
                'db_table': 'quote_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.quoteimage'),
        ),
        migrations.AddField(
            model_name='quote',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
