# Generated by Django 3.2.13 on 2022-11-21 06:15

from django.db import migrations, models
import web.utils.json_handling


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20221118_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_translations',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
    ]
