# Generated by Django 3.2.13 on 2023-02-24 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.utils.json_handling


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_place_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0015_alter_featuredquote_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('default_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_en', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_it', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_es', models.CharField(blank=True, max_length=255, null=True)),
                ('default_cheffe', models.TextField(blank=True, verbose_name='default cheffe')),
                ('cheffe_en', models.TextField(blank=True)),
                ('cheffe_fr', models.TextField(blank=True)),
                ('cheffe_ja', models.TextField(blank=True)),
                ('cheffe_it', models.TextField(blank=True)),
                ('cheffe_es', models.TextField(blank=True)),
                ('status_en', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_fr', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_ja', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_it', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_es', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('cheffe_translations', models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='cheffe_author', to=settings.AUTH_USER_MODEL)),
                ('connected_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_cheffe', to='web.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('default_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('title_it', models.CharField(blank=True, max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('default_username', models.CharField(blank=True, max_length=255, null=True)),
                ('username_en', models.CharField(blank=True, max_length=255, null=True)),
                ('username_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('username_ja', models.CharField(blank=True, max_length=255, null=True)),
                ('username_it', models.CharField(blank=True, max_length=255, null=True)),
                ('username_es', models.CharField(blank=True, max_length=255, null=True)),
                ('default_testimonial', models.TextField(blank=True, verbose_name='default testimonial')),
                ('testimonial_en', models.TextField(blank=True)),
                ('testimonial_fr', models.TextField(blank=True)),
                ('testimonial_ja', models.TextField(blank=True)),
                ('testimonial_it', models.TextField(blank=True)),
                ('testimonial_es', models.TextField(blank=True)),
                ('status_en', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_fr', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_ja', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_it', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('status_es', models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('testimonial_translations', models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='testimonial_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='page_code',
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuredvenue',
            name='slug_ja',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lpb',
            name='slug_ja',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_ja',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='p_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug_it',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='websitepage',
            name='slug_ja',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lpb',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='lpb_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lpb',
            name='status_en',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='lpb',
            name='status_fr',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='lpb',
            name='status_it',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='lpb',
            name='status_ja',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='quote_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='website_page_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status_en',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status_es',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status_fr',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status_it',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AlterField(
            model_name='websitepage',
            name='status_ja',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.abstractimage')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.testimonial')),
            ],
            options={
                'db_table': 'testimonial_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.testimonialimage'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_last_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeaturedTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_fetured', to='news.testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedCheffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('cheffe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheffe_fetured', to='news.cheffe')),
            ],
        ),
        migrations.CreateModel(
            name='CheffeImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.abstractimage')),
                ('cheffe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.cheffe')),
            ],
            options={
                'db_table': 'cheffe_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='cheffe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='news.cheffeimage'),
        ),
        migrations.AddField(
            model_name='cheffe',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheffe_last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
