# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-07 06:12
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200706_0857'),
    ]

    operations = [
        UnaccentExtension()
    ]
