# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0002_auto_20200730_0831'),
        ('web', '0004_auto_20200723_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownersubscription',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_payment_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='purchased_plan_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='web.UserImage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_chargebee.Customer'),
        ),
        migrations.DeleteModel(
            name='OwnerSubscription',
        ),
    ]
