# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 08:19
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Post = apps.get_model("web", "Post")
    for post in Post.objects.filter(venue_id__isnull=False).all():
        post.place_id = post.venue_id
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_place_subscription'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
