# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-20 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200820_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='venue',
        ),
    ]
