# flake8:noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-25 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_post_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.AbstractImage')),
            ],
            options={
                'db_table': 'event_image',
            },
            bases=('web.abstractimage',),
        ),
        migrations.AddField(
            model_name='calevent',
            name='validated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calevent',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_validated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CalEvent'),
        ),
        migrations.AddField(
            model_name='calevent',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='web.EventImage'),
        ),
    ]
