# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200825_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
