# flake8:noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-09 16:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200826_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326),
        ),
    ]
