# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-09-09 17:09
from __future__ import unicode_literals

from django.contrib.gis.geos import Point
from django.db import migrations
from django.db.models import F


def forward(apps, schema_editor):
    Place = apps.get_model("web", "Place")
    places = Place.objects.all()

    for place in places:
        place.point = Point(x=place.longitude, y=place.latitude, srid=4326)
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_place_point'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
