# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-02 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200909_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='cal_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='web.CalEvent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cal_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.CalEvent'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.Place'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.Wine'),
        ),
        migrations.AlterField(
            model_name='likevote',
            name='cal_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_votes', to='web.CalEvent'),
        ),
        migrations.AlterField(
            model_name='likevote',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_votes', to='web.Place'),
        ),
        migrations.AlterField(
            model_name='likevote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_votes', to='web.Post'),
        ),
        migrations.AlterField(
            model_name='likevote',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_votes', to='web.Wine'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='web.Place'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authored', to=settings.AUTH_USER_MODEL),
        ),
    ]
