# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-13 06:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20201002_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='secondary_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, null=True, size=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondary_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, null=True, size=10),
        ),
    ]
