# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20201013_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
