# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-13 08:34
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F

from web.constants import PostStatusE


def forward(apps, schema_editor):
    Post = apps.get_model("web", "Post")
    Post.objects.filter(
        status=PostStatusE.PUBLISHED
    ).update(published_time=F('modified_time'))


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_post_published_time'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
