# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-20 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20201019_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='getmyfreeglass',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_free_glass_objects', to='web.Place'),
        ),
        migrations.AlterField(
            model_name='gotfreeglass',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='got_free_glass_objects', to='web.Place'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='winemaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='web.Winemaker'),
        ),
    ]
