# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-21 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20201020_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.CalEvent'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.Post'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.Post'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vuforiaimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuforia_images', to='web.Post'),
        ),
        migrations.AlterField(
            model_name='vuforiaimage',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuforia_images', to='web.Wine'),
        ),
        migrations.AlterField(
            model_name='wineimage',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.Wine'),
        ),
        migrations.AlterField(
            model_name='winemakerfile',
            name='winemaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web.Winemaker'),
        ),
        migrations.AlterField(
            model_name='winemakerimage',
            name='winemaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.Winemaker'),
        ),
    ]
