# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-22 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20201021_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='external_url',
        ),
    ]
