# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-09 11:19
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Post = apps.get_model("web", "Post")
    Post.objects.filter(is_archived=True).update(status=35)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20201103_2158'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
