# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20201209_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='status',
            field=models.IntegerField(
                choices=[
                    (10, 'ON_HOLD'),
                    (15, 'IN_DOUBT'),
                    (20, 'VALIDATED'),
                    (25, 'REFUSED'),
                    (30, 'BIO_ORGANIC'),
                    (35, 'DELETED'),
                    (40, 'HIDDEN'),
                    (45, 'TO_INVESTIGATE')
                ]
            ),
        ),
    ]
