# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-14 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20210130_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='external_link',
            field=models.BooleanField(default=False),
        ),
    ]
