# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-05-14 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_calevent_external_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calevent',
            old_name='external_link',
            new_name='use_external_link',
        ),
    ]
