# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_calevent_gif_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winelist',
            name='status',
            field=models.IntegerField(choices=[(10, 'ON_HOLD'), (20, 'OK'), (30, 'BG'), (40, 'BG_PROCESSING'), (50, 'FAILED')]),
        ),
    ]
