# Generated by Django 2.0 on 2022-01-11 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('web', '0032_auto_20220111_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='new_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_CITY_MODEL),
        ),
    ]
