# Generated by Django 2.2.16 on 2022-03-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20220117_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='formitable_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
