# Generated by Django 2.0 on 2022-01-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_place_new_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='new_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to=settings.CITIES_CITY_MODEL),
        ),
    ]
