# Generated by Django 2.2.16 on 2022-04-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_userprofile_formitable_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormitableRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('request_data', django.db.models.JSONField(null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Place')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
