# Generated by Django 2.2.16 on 2022-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_formitablerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='formitable_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
