# Generated by Django 2.2.16 on 2022-04-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20220328_2206'),
        ('web', '0035_userprofile_formitable_uid'),
    ]

    operations = [
    ]
