# Generated by Django 2.2.16 on 2022-04-15 12:10

from django.db import migrations, models
import web.utils.filenames


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_merge_20220406_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='is_raisin_participating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calevent',
            name='poster_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=web.utils.filenames.update_event_poster_filename),
        ),
        migrations.AddField(
            model_name='calevent',
            name='tickets_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calevent',
            name='wine_faire_url',
            field=models.TextField(null=True),
        ),
    ]
