# Generated by Django 2.2.16 on 2022-04-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20220111_0721'),
        ('web', '0037_auto_20220415_1210'),
    ]

    operations = [
    ]
