# Generated by Django 2.2.16 on 2022-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20220415_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='src_info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
