# Generated by Django 2.2.28 on 2022-05-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_auto_20220509_1801'),
        ('web', '0038_merge_20220420_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='cities.District'),
        ),
    ]
