# Generated by Django 2.2.28 on 2022-04-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_place_src_info'),
        ('web', '0038_merge_20220420_1038'),
    ]

    operations = [
    ]
