# Generated by Django 2.2.28 on 2022-05-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_merge_20220422_0936'),
        ('web', '0039_place_district'),
    ]

    operations = [
    ]
