# Generated by Django 3.2.13 on 2022-07-01 10:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='cached_item',
            field=django.db.models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
