# Generated by Django 3.2.13 on 2022-07-13 15:48

from django.db import migrations, models
import web.utils.json_handling


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20220705_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuserstorage',
            name='stored_data',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_mentions',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='extra_json',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='resp_item_json',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='donationreceipt',
            name='provider_response',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='formitablerequest',
            name='request_data',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='monthlystatssubscriberplace',
            name='daily_stats',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='monthlystatssubscriberplace',
            name='last_week_stats',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='monthlystatssubscriberplace',
            name='this_week_stats',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='closing_dates',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_hours',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='user_mentions',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_mentions',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='yearly_data',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='cached_item',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='winelist',
            name='total_score_data',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='winelistfile',
            name='item_text_rows',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='domain_description_translations',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='user_mentions',
            field=models.JSONField(encoder=web.utils.json_handling.JsonEncoder, null=True),
        ),
    ]
