# Generated by Django 2.2.28 on 2022-07-11 06:22

from django.conf import settings
from django.db import migrations, models
from web.utils.default_data import get_erased_user_uid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20220705_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractimage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cmsadmincomment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='comments_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=models.SET(get_erased_user_uid()), related_name='comments_where_replied_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drankittoo',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='drank_it_toos_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likevote',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='like_votes_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='posts_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelineitem',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='timeline_item_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='user_notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winelistfile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winemaker',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
    ]
