# Generated by Django 3.2.13 on 2022-07-15 09:01

from django.conf import settings
from django.db import migrations, models
from web.utils.default_data import get_erased_user_uid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20220713_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='external_submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET(get_erased_user_uid()), to=settings.AUTH_USER_MODEL),
        ),
    ]
