# Generated by Django 2.2.28 on 2022-07-11 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.utils.filenames
from web.utils.default_data import get_erased_user_uid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20220711_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title EN')),
                ('title_fr', models.CharField(blank=True, max_length=200, verbose_name='title FR')),
                ('title_ja', models.CharField(blank=True, max_length=200, verbose_name='title JA')),
                ('title_it', models.CharField(blank=True, max_length=200, verbose_name='title IT')),
                ('title_es', models.CharField(blank=True, max_length=200, verbose_name='title ES')),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_fr', models.TextField(blank=True)),
                ('meta_description_ja', models.TextField(blank=True)),
                ('meta_description_it', models.TextField(blank=True)),
                ('meta_description_es', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_fr', models.TextField(blank=True)),
                ('content_ja', models.TextField(blank=True)),
                ('content_it', models.TextField(blank=True)),
                ('content_es', models.TextField(blank=True)),
                ('published_en', models.BooleanField(default=False)),
                ('published_fr', models.BooleanField(default=False)),
                ('published_ja', models.BooleanField(default=False)),
                ('published_it', models.BooleanField(default=False)),
                ('published_es', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster_image_file', models.ImageField(blank=True, null=True, upload_to=web.utils.filenames.update_news_poster_filename)),
                ('gif_image_file', models.ImageField(blank=True, null=True, upload_to=web.utils.filenames.update_news_gif_filename)),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET(get_erased_user_uid()), related_name='news_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),


        migrations.AddField(
            model_name='news',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_last_editor', to=settings.AUTH_USER_MODEL),
        ),

    ]
