# Generated by Django 2.2.28 on 2022-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_auto_20220711_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_type',
            field=models.CharField(default='news', max_length=200, verbose_name='type'),
        ),
    ]
