# Generated by Django 2.2.28 on 2022-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_news_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='news',
            name='gif_image_file',
        ),
        migrations.RemoveField(
            model_name='news',
            name='poster_image_file',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_es',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_fr',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_it',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_ja',
        ),
        migrations.AddField(
            model_name='news',
            name='status_en',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AddField(
            model_name='news',
            name='status_es',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AddField(
            model_name='news',
            name='status_fr',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AddField(
            model_name='news',
            name='status_it',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
        migrations.AddField(
            model_name='news',
            name='status_ja',
            field=models.CharField(blank=True, default=10, max_length=200, verbose_name='title ES'),
        ),
    ]
