# Generated by Django 3.2.13 on 2022-07-26 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20220725_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
