# Generated by Django 2.2.28 on 2022-07-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_news_deleted'),
    ]

    operations = [

    ]
