# Generated by Django 2.2.28 on 2022-07-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20220712_0542'),
    ]

    operations = [

    ]
