# Generated by Django 2.2.28 on 2022-07-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_likevote_news'),
    ]

    operations = [

    ]
