# Generated by Django 2.2.28 on 2022-07-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_remove_news_article_type'),
    ]

    operations = [
        
    ]
