# Generated by Django 2.2.28 on 2022-07-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20220714_1231'),
    ]

    operations = [

    ]
