# Generated by Django 2.2.28 on 2022-07-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_auto_20220714_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
