# Generated by Django 2.2.28 on 2022-07-15 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220715_0630'),
        ('web', '0055_auto_20220714_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='featured_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.FeaturedVenue'),
        ),
        migrations.AddField(
            model_name='likevote',
            name='featured_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_votes', to='news.FeaturedVenue'),
        ),
    ]
