# Generated by Django 3.2.13 on 2022-07-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_usernotification_user'),
        ('web', '0058_auto_20220726_0728'),
    ]

    operations = [
    ]
