# Generated by Django 3.2.16 on 2022-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_auto_20220916_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='tickets_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='wine_faire_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
