# Generated by Django 3.2.13 on 2022-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_auto_20220916_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='winelist',
            name='is_in_shared_pool',
            field=models.BooleanField(default=False),
        ),
    ]
