# Generated by Django 3.2.16 on 2022-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_auto_20221121_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calevent',
            name='loc_city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='loc_full_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='loc_house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='loc_street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='loc_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
