# Generated by Django 3.2.13 on 2022-11-01 17:17

from django.db import migrations, models
from web.models import validate_word_caseinsensitive


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_winelist_is_in_shared_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwlaexcludedword',
            name='word',
            field=models.CharField(max_length=255, unique=True, validators=[validate_word_caseinsensitive]),
        ),
    ]
