# Generated by Django 3.2.13 on 2022-12-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_alter_nwlaexcludedword_word'),
        ('web', '0065_alter_calevent_loc_name'),
    ]

    operations = [
    ]
