# Generated by Django 3.2.13 on 2023-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_merge_20221230_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='osm_city_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
