# Generated by Django 3.2.13 on 2023-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_place_osm_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='osm_country_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
