# Generated by Django 3.2.13 on 2023-03-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_place_slug'),
        ('web', '0068_place_osm_country_name'),
    ]

    operations = [
    ]
