# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-23 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('billing_address', django.db.models.JSONField(null=True)),
                ('company', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('locale', models.CharField(max_length=20, null=True)),
                ('phone', models.TextField(null=True)),
                ('payment_method', django.db.models.JSONField(null=True)),
                ('preferred_currency_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(choices=[(1, 'processed'), (0, 'not processed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('addons', django.db.models.JSONField(null=True)),
                ('auto_collection', models.CharField(default='off', max_length=10)),
                ('billing_period', models.IntegerField(null=True)),
                ('billing_period_unit', models.CharField(max_length=10, null=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('mrr', models.FloatField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('plan_unit_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(max_length=20)),
                ('plan_id', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_chargebee.Customer')),
            ],
        ),
    ]
