# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-05 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0002_auto_20200730_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('is_deleted_from_chargebee', models.BooleanField(default=False)),
                ('currency_code', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'paid'), ('posted', 'posted'), ('payment_due', 'payment_due'), ('not_paid', 'not_paid'), ('voided', 'voided'), ('pending', 'pending')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted_from_chargebee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted_from_chargebee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted_from_chargebee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_chargebee.Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_chargebee.Subscription'),
        ),
    ]
