# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-13 10:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0003_auto_20200805_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=django.db.models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='occurred_at',
            field=models.DateTimeField(null=True),
        ),
    ]
