# Generated by Django 2.2.16 on 2022-03-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0004_auto_20200813_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='addons',
            new_name='event_based_addons',
        ),
    ]
