# Generated by Django 2.2.16 on 2022-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0005_auto_20220328_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='primary_payment_source_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
