# Generated by Django 2.2.16 on 2022-03-29 15:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0006_customer_primary_payment_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='shipping_address',
            field=django.db.models.JSONField(null=True),
        ),
    ]
