# Generated by Django 2.2.16 on 2022-03-31 17:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0007_subscription_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('is_deleted_from_chargebee', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('card', 'card'), ('paypal_express_checkout', 'paypal_express_checkout'), ('amazon_payments', 'amazon_payments'), ('direct_debit', 'direct_debit'), ('generic', 'generic'), ('alipay', 'alipay'), ('unionpay', 'unionpay'), ('apple_pay', 'apple_pay'), ('wechat_pay', 'wechat_pay'), ('ideal', 'ideal'), ('google_pay', 'google_pay'), ('sofort', 'sofort'), ('bancontact', 'bancontact'), ('giropay', 'giropay'), ('dotpay', 'dotpay'), ('upi', 'upi'), ('netbanking_emandates', 'netbanking_emandates')], max_length=23)),
                ('status', models.CharField(choices=[('valid', 'valid'), ('expiring', 'expiring'), ('expired', 'expired'), ('invalid', 'invalid'), ('pending_verification', 'pending_verification')], default='valid', max_length=20)),
                ('card', django.db.models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_chargebee.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
