# Generated by Django 2.2.16 on 2022-04-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0008_paymentsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
