# Generated by Django 2.2.28 on 2022-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chargebee', '0010_auto_20220401_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auto_collection',
            field=models.CharField(default='n.d.', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_collection',
            field=models.CharField(default='n.d.', max_length=10),
        ),
    ]
