from django.conf.urls import url
from . import ajax_mass_operation_views
from . import views
from news import ajax_views


urls_ajax_lists = [
    url(
        r'^news/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        views.news_related_lists,
        name='news_related_lists_ajax'
    ),
    url(
        r'^news/items$',
        views.get_news_items,
        name='get_news_items_ajax'
    ),
    url(
        r'^news/publish',
        ajax_mass_operation_views.news_publish,
        name='news_publish_ajax'
    ),
    url(
        r'^news/merge',
        ajax_mass_operation_views.news_merge,
        name='news_merge_ajax'
    ),
    url(
        r'^news/unpublish',
        ajax_mass_operation_views.news_unpublish,
        name='news_unpublish_ajax'
    ),
    url(
        r'^news/delete',
        ajax_mass_operation_views.news_delete,
        name='news_delete_ajax'
    ),
    url(
        r'^featured-venue/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        views.featured_venue_related_lists,
        name='featured_venue_related_lists_ajax'
    ),
    url(
        r'^featured-venue/items$',
        views.get_featured_venue_items,
        name='get_featured_venue_items_ajax'
    ),
    url(
        r'^featured-venue/publish',
        ajax_mass_operation_views.featured_venue_publish,
        name='featured_venue_publish_ajax'
    ),
    url(
        r'^featured-venue/merge',
        ajax_mass_operation_views.featured_venue_merge,
        name='featured_venue_merge_ajax'
    ),
    url(
        r'^featured-venue/unpublish',
        ajax_mass_operation_views.featured_venue_unpublish,
        name='featured_venue_unpublish_ajax'
    ),
    url(
        r'^featured-venue/delete',
        ajax_mass_operation_views.featured_venue_delete,
        name='featured_venue_delete_ajax'
    ),
    url(
        r'^website-page/items$',
        views.get_website_page_items,
        name='get_website_page_items_ajax'
    ),
    url(
        r'^lpb/publish',
        ajax_mass_operation_views.lpb_publish,
        name='lpb_publish_ajax'
    ),
    url(
        r'^lpb/unpublish',
        ajax_mass_operation_views.lpb_unpublish,
        name='lpb_unpublish_ajax'
    ),
    url(
        r'^lpb/delete',
        ajax_mass_operation_views.lpb_delete,
        name='lpb_delete_ajax'
    ),
    url(
        r'^lpb/items$',
        views.get_lpb_items,
        name='get_lpb_items_ajax'
    ),
    url(
        r'^quote/items$',
        views.get_quote_items,
        name='get_quote_items_ajax'
    ),
    url(
        r'^quote/publish',
        ajax_mass_operation_views.quote_publish,
        name='quote_publish_ajax'
    ),
    url(
        r'^quote/unpublish',
        ajax_mass_operation_views.quote_unpublish,
        name='quote_unpublish_ajax'
    ),
    url(
        r'^quote/delete',
        ajax_mass_operation_views.quote_delete,
        name='quote_delete_ajax'
    ),
    url(
        r'^quote/translate-quote',
        ajax_views.translate_quote,
        name="translate_quote_ajax"
    ),
    url(
        r'^quote/clear-quote-translations',
        ajax_views.clear_quote_translations,
        name="clear_quote_ajax"
    ),
    url(
        r'^testimonial/items$',
        views.get_testimonial_items,
        name='get_testimonial_items_ajax'
    ),
    url(
        r'^testimonial/publish',
        ajax_mass_operation_views.testimonial_publish,
        name='testimonial_publish_ajax'
    ),
    url(
        r'^testimonial/unpublish',
        ajax_mass_operation_views.testimonial_unpublish,
        name='testimonial_unpublish_ajax'
    ),
    url(
        r'^testimonial/delete',
        ajax_mass_operation_views.testimonial_delete,
        name='testimonial_delete_ajax'
    ),
    url(
        r'^testimonial/translate-testimonial',
        ajax_views.translate_testimonial,
        name="translate_testimonial_ajax"
    ),
    url(
        r'^testimonial/clear-testimonial-translations',
        ajax_views.clear_testimonial_translations,
        name="clear_testimonial_ajax"
    ),
    url(
        r'^cheffe/items$',
        views.get_cheffe_items,
        name='get_cheffe_items_ajax'
    ),
    url(
        r'^cheffe/publish',
        ajax_mass_operation_views.cheffe_publish,
        name='cheffe_publish_ajax'
    ),
    url(
        r'^cheffe/unpublish',
        ajax_mass_operation_views.cheffe_unpublish,
        name='cheffe_unpublish_ajax'
    ),
    url(
        r'^cheffe/delete',
        ajax_mass_operation_views.cheffe_delete,
        name='cheffe_delete_ajax'
    ),
    url(
        r'^cheffe/translate-cheffe',
        ajax_views.translate_cheffe,
        name="translate_cheffe_ajax"
    ),
    url(
        r'^cheffe/clear-cheffe-translations',
        ajax_views.clear_cheffe_translations,
        name="clear_cheffe_ajax"
    ),
    url(
        r'^testimonials/testimonials-autocomplete',
        ajax_views.testimonials_autocomplete,
        name="testimonials_autocomplete"
    ),
]
