from django.conf.urls import url

from my_chargebee import views as chargebee_views
from web.views.ajax import (ajax_autocomplete_views, ajax_image_views,
                            ajax_mass_operation_views, ajax_views,
                            ajax_winelist_views, ajax_winepost_views,
                            ajax_winefaire_views)
from web.views.ajax_lists import (comment_views, donation_views, est_com_views,
                                  est_free_glass_views, event_views,
                                  general_post_views, place_views,
                                  related_list_views, user_views,
                                  winemaker_views, winepost_views, like_views)

urls_ajax_lists = [
    url(
        r'^users/resetpass$',
        ajax_views.reset_password,
        name='reset_password_ajax'
    ),

    # ------------------------- AJAX autocompletes -------------------------
    url(
        r'^autocomplete/address/textsearch$',
        ajax_autocomplete_views.autocomplete_address_textsearch,
        name="autocomplete_address_textsearch_ajax"
    ),
    url(
        r'^autocomplete/address/place_id',
        ajax_autocomplete_views.autocomplete_address_place_id,
        name="autocomplete_address_place_id_ajax"
    ),
    url(
        r'^autocomplete/winemaker/$',
        ajax_autocomplete_views.autocomplete_winemaker,
        name="autocomplete_winemaker_ajax"
    ),
    url(
        r'^autocomplete/domain/$',
        ajax_autocomplete_views.autocomplete_domain,
        name="autocomplete_domain_ajax"
    ),
    url(
        r'^autocomplete/domain_by_winemaker/$',
        ajax_autocomplete_views.get_domain_name,
        name="autocomplete_domain_by_winemaker_ajax"
    ),
    url(
        r'^autocomplete/wine/$',
        ajax_autocomplete_views.autocomplete_wine,
        name="autocomplete_wine_ajax"),
    url(
        r'^autocomplete/place/$',
        ajax_autocomplete_views.autocomplete_place,
        name="autocomplete_place_ajax"
    ),
    url(
        r'^autocomplete/username/$',
        ajax_autocomplete_views.autocomplete_username,
        name="autocomplete_username_ajax"
    ),

    # ------------------ AJAX update domain description ------------------

    url(
        r'^winemaker/translate-domain-description',
        ajax_views.translate_domain_description,
        name="translate_domain_description_ajax"
    ),
    url(
        r'^winemaker/clear-domain-description-translations',
        ajax_views.clear_domain_description_translations,
        name="clear_domain_description_translations_ajax"
    ),
    url(
        r'^winemaker/update-domain-description-translations',
        ajax_views.update_domain_description_translations,
        name="update_domain_description_translations_ajax"
    ),
    url(
        r'^autocomplete/update_original_winemaker_name',
        ajax_autocomplete_views.update_original_winemaker_name,
        name="update_original_winemaker_name_ajax"
    ),

    url(
        r'^autocomplete/change-parent-post-winemaker-list',
        ajax_autocomplete_views.change_parent_post_winemaker_list,
        name="change_parent_post_winemaker_list_ajax"
    ),

    url(
        r'^autocomplete/change_parent_post_list_winemaker/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_autocomplete_views.change_parent_post_list_winemaker,
        name="change_parent_post_list_winemaker_ajax"
    ),

    url(
        r'^autocomplete/change-parent-post-wine-list',
        ajax_autocomplete_views.change_parent_post_wine_list,
        name="change_parent_post_wine_list_ajax"
    ),

    # DEFINE AS CHILDREN - old name was "change_parent_post"
    # keeping url and url name
    url(
        r'^autocomplete/change-parent-post',
        ajax_winepost_views.define_as_children,
        name="change_parent_post_ajax"),

    # --------------------------- AJAX widgets ---------------------------

    url(
        r'^ajax/winemaker/wine/add/widget/(?P<initial_row_number>[0-9A-Za-z_\-]+)/',  # noqa
        ajax_views.get_add_wine_widget,
        name="get_add_wine_widget_ajax"),

    # --------------------------- AJAX winelist ---------------------------

    url(
        r'^ajax/winelist/items/list/(?P<pid>[0-9A-Za-z_\-]+)/$',
        ajax_winelist_views.get_winelist_items,
        name="get_winelist_items_ajax"
    ),
    url(
        r'^ajax/right-panel/winelist/items/list/(?P<pid>[0-9A-Za-z_\-]+)/$',
        ajax_winelist_views.get_winelist_items_for_right_panel,
        name="get_winelist_items_ajax_for_right_panel"
    ),
    url(
        r'^ajax/winelist/temp/items/list/(?P<pid>[0-9A-Za-z_\-]+)/$',
        ajax_winelist_views.get_winelist_temp_items,
        name="get_winelist_temp_items_ajax"
    ),
    url(
        r'^ajax/winelist/shared/items/list/$',
        ajax_winelist_views.get_winelist_shared_items,
        name="get_winelist_shared_items_ajax"
    ),
    url(
        r'^ajax/winelist/item/get/(?P<id>[0-9A-Za-z_\-]+)/$',
        ajax_winelist_views.get_winelist_item,
        name="get_winelist_item_ajax"
    ),
    url(
        r'^ajax/winelist/item/update/$',
        ajax_winelist_views.update_winelist_item,
        name="update_winelist_item_ajax"
    ),
    url(
        r'^ajax/winelist/item/delete/$',
        ajax_winelist_views.delete_winelist_item,
        name="delete_winelist_item_ajax"
    ),
    url(
        r'^ajax/winelist/item/upload/$',
        ajax_winelist_views.upload_winelist_item,
        name="upload_winelist_item_ajax"
    ),
    url(
        r'^ajax/winelist/refresh_place_score/(?P<pid>[0-9A-Za-z_\-]+)/$',
        ajax_winelist_views.refresh_place_score,
        name="refresh_place_score_ajax"),

    # --------------------------- AJAX images ---------------------------

    url(
        r'^ajax/image/vuforia/get/(?P<pid>[0-9]+)$',
        ajax_image_views.get_vuforia_image,
        name="get_vuforia_image_ajax"
    ),
    url(
        r'^ajax/image/ordering/place/update/$',
        ajax_image_views.image_update_ordering_place,
        name="image_update_ordering_place_ajax"
    ),
    url(
        r'^ajax/image/ordering/winemaker/update/$',
        ajax_image_views.image_update_ordering_winemaker,
        name="image_update_ordering_winemaker_ajax"
    ),

    # -------------------------- delete image
    url(
        r'^ajax/images/wm-other-files/temp/delete/(?P<dir_name>[0-9A-Za-z_\-]+)/',  # noqa
        ajax_image_views.delete_wm_file_temp,
        name="delete_wm_file_temp_ajax"
    ),
    url(
        r'^ajax/images/wm-other-files/delete/',
        ajax_image_views.delete_wm_file, name="delete_wm_file_ajax"
    ),
    url(
        r'^ajax/images/winepost-other-files/delete/',
        ajax_image_views.delete_winepost_file, name="delete_winepost_file_ajax"
    ),
    url(
        r'^ajax/images/winemaker/temp/delete/(?P<dir_name>[0-9A-Za-z_\-]+)/',
        ajax_image_views.delete_image_winemaker_temp,
        name="delete_image_winemaker_temp_ajax"
    ),
    url(
        r'^ajax/images/winemaker/delete/',
        ajax_image_views.delete_image_winemaker,
        name="delete_image_winemaker_ajax"
    ),
    url(
        r'^ajax/images/wine/temp/delete/(?P<dir_name>[0-9A-Za-z_\-]+)/',
        ajax_image_views.delete_image_wine_temp,
        name="delete_image_wine_temp_ajax"
    ),
    url(
        r'^ajax/images/wine/delete/',
        ajax_image_views.delete_image_wine, name="delete_image_wine_ajax"
    ),
    url(
        r'^ajax/images/place/temp/delete/(?P<dir_name>[0-9A-Za-z_\-]+)/',
        ajax_image_views.delete_image_place_temp,
        name="delete_image_place_temp_ajax"
    ),
    url(
        r'^ajax/images/place/delete/',
        ajax_image_views.delete_image_place, name="delete_image_place_ajax"
    ),

    # -------------------------- current images
    url(
        r'^ajax/images/wm-other-files/temp/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_temp_wm_files,
        name="current_temp_wm_files_ajax"
    ),
    url(
        r'^ajax/images/wm-other-files/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_wm_files,
        name="current_wm_files_ajax"
    ),
    url(
        r'^ajax/images/winepost-other-files/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_winepost_files,
        name="current_winepost_files_ajax"
    ),
    url(
        r'^ajax/images/winemaker/temp/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_temp_images_winemaker,
        name="current_images_winemaker_temp_ajax"
    ),
    url(
        r'^ajax/images/winemaker/current/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_images_winemaker,
        name="current_images_winemaker_ajax"
    ),
    url(
        r'^ajax/images/wine/temp/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_temp_images_wine,
        name="current_images_wine_temp_ajax"
    ),
    url(
        r'^ajax/images/wine/current/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_images_wine,
        name="current_images_wine_ajax"
    ),
    url(
        r'^ajax/images/place/temp/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_temp_images_place,
        name="current_images_place_temp_ajax"
    ),
    url(
        r'^ajax/images/place/current/(?P<id>[0-9A-Za-z_\-]+)/',
        ajax_image_views.current_images_place,
        name="current_images_place_ajax"
    ),
    # -------------------------- upload images
    url(
        r'^image/upload/wm-other-files/temp/$',
        ajax_image_views.upload_wm_file_temp,
        name='upload_wm_file_temp_ajax'
    ),
    url(
        r'^image/upload/wm-other-files/$',
        ajax_image_views.upload_wm_file,
        name='upload_wm_file_ajax'
    ),
    url(
        r'^image/upload/winepost-ref-image/$',
        ajax_image_views.upload_winepost_ref_image,
        name='upload_winepost_ref_image_ajax'
    ),
    url(
        r'^image/set-as-vuforia/$',
        ajax_image_views.set_as_vuforia,
        name='set_as_vuforia_ajax'
    ),
    url(
        r'^image/refresh-vuforia-image/$',
        ajax_image_views.refresh_vuforia_image,
        name='refresh_vuforia_image_ajax'
    ),
    url(
        r'^image/upload/winepost-other-files/$',
        ajax_image_views.upload_winepost_file,
        name='upload_winepost_file_ajax'
    ),
    url(
        r'^image/upload/winemaker/$',
        ajax_image_views.image_upload_winemaker,
        name='image_upload_winemaker_ajax'
    ),
    url(
        r'^image/upload/winemaker/temp/$',
        ajax_image_views.image_upload_winemaker_temp,
        name='image_upload_winemaker_temp_ajax'
    ),
    url(
        r'^image/upload/wine/$',
        ajax_image_views.image_upload_wine,
        name='image_upload_wine_ajax'
    ),
    url(
        r'^image/upload/wine/temp/$',
        ajax_image_views.image_upload_wine_temp,
        name='image_upload_wine_temp_ajax'
    ),
    url(
        r'^image/upload/place/$',
        ajax_image_views.image_upload_place,
        name='image_upload_place_ajax'
    ),
    url(
        r'^image/upload/place/temp/$',
        ajax_image_views.image_upload_place_temp,
        name='image_upload_place_temp_ajax'
    ),
    url(
        r'^convert-heic/$',
        ajax_image_views.convert_heic,
        name='convert_heic'
    ),

    # --------------------------- AJAX lists ---------------------------

    url(
        r'^winepost/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        related_list_views.winepost_related_lists,
        name='winepost_related_lists_ajax'
    ),
    url(
        r'^place/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        related_list_views.place_related_lists,
        name='place_related_lists_ajax'
    ),
    url(
        r'^event/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        related_list_views.event_related_lists,
        name='event_related_lists_ajax'
    ),
    url(
        r'^post/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        related_list_views.generalpost_related_lists,
        name='generalpost_related_lists_ajax'
    ),
    url(
        r'^food/related-lists/(?P<id>[0-9A-Za-z_\-]+)/$',
        related_list_views.food_related_lists,
        name='food_related_lists_ajax'
    ),
    url(
        r'^place/subscription/$',
        chargebee_views.get_subscription_details,
        name='get_subscription_details'
    ),
    url(
        r'^place/items-opti/(?P<list_for>[A-Za-z_\-]+)/$',
        place_views.get_place_items_opti,
        name='get_place_items_opti_ajax'
    ),
    url(
        r'^place/subscribers',
        place_views.get_place_subscribers_items,
        name='get_place_subscribers_items_ajax'
    ),
    url(
        r'^winepost/items/winepost-vuforia/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_items_for_winepost_vuforia,
        name='get_winepost_items_for_winepost_vuforia_ajax'
    ),
    url(
        r'^winepost/delete-yearly-data/$',
        ajax_winepost_views.delete_yearly_data,
        name='delete_yearly_data_ajax'
    ),
    url(
        r'^winepost/update-yearly-data/$',
        ajax_winepost_views.update_yearly_data,
        name='update_yearly_data_ajax'
    ),
    url(
        r'^winepost/fetch-yearly-data/$',
        ajax_winepost_views.fetch_yearly_data,
        name='fetch_yearly_data_ajax'
    ),
    url(
        r'^all-referees/',
        winepost_views.get_all_referee_items,
        name='get_all_referee_items'
    ),
    url(
        r'^all-star-reviews/',
        winepost_views.get_all_star_review_items,
        name='get_all_star_review_items'
    ),
    url(
        r'^winepost/referee-items/winepost/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_referee_items_for_winepost,
        name='get_winepost_referee_items_for_winepost_ajax'
    ),
    url(
        r'^winepost/referee-items/wine/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_referee_items_for_wine,
        name='get_winepost_referee_items_for_wine_ajax'
    ),
    url(
        r'^winepost/star-reviews/wine/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_star_review_items_for_wine,
        name='get_winepost_star_review_items_for_wine_ajax'
    ),
    url(
        r'^winepost/referee-items/winemaker/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_referee_items_for_winemaker,
        name='get_winepost_referee_items_for_winemaker_ajax'
    ),
    url(
        r'^winepost/star-reviews/winemaker/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_star_review_items_for_winemaker,
        name='get_winepost_star_review_items_for_winemaker_ajax'
    ),
    url(
        r'^winepost/items/winemaker/(?P<id>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_winepost_items_for_winemaker,
        name='get_winepost_items_for_winemaker_ajax'
    ),
    url(
        r'^winepost/items-opti/(?P<list_for>[A-Za-z]+)/$',
        winepost_views.get_winepost_items_opti,
        name='get_winepost_items_opti_ajax'),
    url(
        r'^est-com/items$',
        est_com_views.get_est_com_items,
        name='get_est_com_items_ajax'
    ),
    url(
        r'^est-free-glass/items$',
        est_free_glass_views.get_est_free_glass_items,
        name='get_est_free_glass_items_ajax'
    ),
    url(
        r'^event/items$',
        event_views.get_event_items,
        name='get_event_items_ajax'
    ),
    url(
        r'^post/items$',
        general_post_views.get_general_post_items,
        name='get_general_post_items_ajax'
    ),
    url(
        r'^food/items$',
        general_post_views.get_food_items,
        name='get_food_items_ajax'
    ),
    url(
        r'^winemaker/items/all$',
        winemaker_views.get_winemaker_items_all,
        name='get_winemaker_items_all_ajax'
    ),
    url(
        r'^winemaker/items/naturals$',
        winemaker_views.get_winemaker_items_naturals,
        name='get_winemaker_items_naturals_ajax'
    ),
    url(
        r'^winemaker/items/others$',
        winemaker_views.get_winemaker_items_others,
        name='get_winemaker_items_others_ajax'
    ),
    url(
        r'^user/items$',
        user_views.get_user_items,
        name='get_user_items_ajax'
    ),
    url(
        r'^userpost/items/(?P<uid>[0-9A-Za-z_\-]+)/$',
        winepost_views.get_userpost_items,
        name='get_user_post_items_ajax'
    ),
    url(
        r'^userplace/items/(?P<uid>[0-9A-Za-z_\-]+)/$',
        place_views.get_userplace_items,
        name='get_user_place_items_ajax'
    ),
    url(
        r'^usercomment/items/(?P<uid>[0-9A-Za-z_\-]+)/$',
        comment_views.get_usercomment_items,
        name='get_user_comment_items_ajax'
    ),
    # ------------------------- AJAX mass operations --------------------------

    # places
    url(
        r'^places/publish',
        ajax_mass_operation_views.places_publish,
        name='places_publish_ajax'
    ),
    url(
        r'^places/unpublish',
        ajax_mass_operation_views.places_unpublish,
        name='places_unpublish_ajax'
    ),
    url(
        r'^places/delete',
        ajax_mass_operation_views.places_delete,
        name='places_delete_ajax'
    ),
    url(
        r'^places/duplicate',
        ajax_mass_operation_views.places_duplicate,
        name='places_duplicate_ajax'
    ),
    url(
        r'^places/close',
        ajax_mass_operation_views.places_close,
        name='places_close_ajax'
    ),
    url(
        r'^places/set_in_doubt',
        ajax_mass_operation_views.places_set_in_doubt,
        name='places_set_in_doubt_ajax'
    ),
    url(
        r'^autocomplete/place/published/list',
        ajax_autocomplete_views.published_places_list,
        name='published_places_list_ajax'
    ),
    url(
        r'^autocomplete/place/subscriptions/list',
        ajax_autocomplete_views.subscriptions_list,
        name='subscriptions_list_ajax'
    ),
    url(
        r'^autocomplete/place/for-featured-venue',
        ajax_autocomplete_views.autocomplete_place_for_featured_venue,
        name='autocomplete_place_for_featured_venue_api'
    ),
    # wineposts
    url(
        r'^wineposts/publish',
        ajax_mass_operation_views.wineposts_publish,
        name='wineposts_publish_ajax'
    ),
    url(
        r'^wineposts/unpublish',
        ajax_mass_operation_views.wineposts_unpublish,
        name='wineposts_unpublish_ajax'
    ),
    url(
        r'^wineposts/delete',
        ajax_mass_operation_views.wineposts_delete,
        name='wineposts_delete_ajax'
    ),
    url(
        r'^wineposts/undelete',
        ajax_mass_operation_views.wineposts_undelete,
        name='wineposts_undelete_ajax'
    ),
    url(
        r'^wineposts/refuse',
        ajax_mass_operation_views.wineposts_refuse,
        name='wineposts_refuse_ajax'
    ),
    url(
        r'^wineposts/set_in_doubt',
        ajax_mass_operation_views.wineposts_set_in_doubt,
        name='wineposts_set_in_doubt_ajax'
    ),
    url(
        r'^wineposts/set_to_investigate',
        ajax_mass_operation_views.wineposts_set_to_investigate,
        name='wineposts_set_to_investigate'
    ),
    url(
        r'^wineposts/set_bio_organic',
        ajax_mass_operation_views.wineposts_set_bio_organic,
        name='wineposts_set_bio_organic_ajax'
    ),
    url(
        r'^winemakers/set_bio_organic',
        ajax_mass_operation_views.winemakers_set_bio_organic,
        name='winemakers_set_bio_organic_ajax'
    ),
    url(
        r'^winemakers/set_to_investigate',
        ajax_mass_operation_views.winemakers_set_to_investigate,
        name='winemakers_set_to_investigate_ajax'
    ),

    url(
        r'^wineposts/mop-define-as-children',
        ajax_mass_operation_views.wineposts_mop_define_as_children,
        name='wineposts_mop_define_as_children_ajax'
    ),
    url(
        r'^wineposts/mop-has-children',
        ajax_mass_operation_views.winepost_has_children,
        name='wineposts_mop_has_children_ajax'
    ),
    url(
        r'^wineposts/mop-move-to-general-post',
        ajax_mass_operation_views.wineposts_mop_move_to_general_post,
        name='wineposts_mop_move_to_general_post_ajax'
    ),
    url(
        r'^est-com/delete',
        ajax_mass_operation_views.est_com_delete,
        name='est_com_delete_ajax'
    ),
    url(
        r'^est-com/undelete',
        ajax_mass_operation_views.est_com_undelete,
        name='est_com_undelete_ajax'
    ),
    url(
        r'^est-com/ban-user',
        ajax_mass_operation_views.est_com_ban_user,
        name='est_com_ban_user_ajax'
    ),
    url(
        r'^est-com/unban-user',
        ajax_mass_operation_views.est_com_unban_user,
        name='est_com_unban_user_ajax'
    ),
    url(
        r'^wines/delete',
        ajax_mass_operation_views.wines_delete,
        name='wine_delete_ajax'
    ),
    url(
        r'^generalposts/publish',
        ajax_mass_operation_views.generalposts_publish,
        name='generalposts_publish_ajax'
    ),
    url(
        r'^food/publish',
        ajax_mass_operation_views.food_publish,
        name='food_publish_ajax'
    ),
    url(
        r'^event/publish',
        ajax_mass_operation_views.event_publish,
        name='event_publish_ajax'
    ),
    url(
        r'^generalposts/unpublish',
        ajax_mass_operation_views.generalposts_unpublish,
        name='generalposts_unpublish_ajax'
    ),
    url(
        r'^food/unpublish',
        ajax_mass_operation_views.food_unpublish,
        name='food_unpublish_ajax'
    ),
    url(
        r'^event/unpublish',
        ajax_mass_operation_views.event_unpublish,
        name='event_unpublish_ajax'
    ),
    url(
        r'^generalposts/refuse',
        ajax_mass_operation_views.generalposts_refuse,
        name='generalposts_refuse_ajax'
    ),
    url(
        r'^food/refuse',
        ajax_mass_operation_views.food_refuse,
        name='food_refuse_ajax'
    ),
    url(
        r'^event/refuse',
        ajax_mass_operation_views.event_refuse,
        name='event_refuse_ajax'
    ),
    url(
        r'^winemakers/publish',
        ajax_mass_operation_views.winemakers_publish,
        name='winemakers_publish_ajax'
    ),
    url(
        r'^winemakers/unpublish',
        ajax_mass_operation_views.winemakers_unpublish,
        name='winemakers_unpublish_ajax'
    ),
    url(
        r'^winemakers/set_in_doubt',
        ajax_mass_operation_views.winemakers_set_in_doubt,
        name='winemakers_set_in_doubt_ajax'
    ),
    url(
        r'^winemakers/delete',
        ajax_mass_operation_views.winemakers_delete,
        name='winemakers_delete_ajax'
    ),
    url(
        r'^winemakers/duplicate',
        ajax_mass_operation_views.winemakers_duplicate,
        name='winemakers_duplicate_ajax'
    ),
    url(
        r'^users/ban',
        ajax_mass_operation_views.users_ban,
        name='users_ban_ajax'
    ),
    url(
        r'^users/unban',
        ajax_mass_operation_views.users_unban,
        name='users_unban_ajax'
    ),
    url(
        r'^comments/delete',
        ajax_mass_operation_views.comments_delete,
        name='comments_delete_ajax'
    ),
    url(
        r'^comments/edit-open',
        comment_views.comments_edit_open,
        name='comments_edit_open_ajax'
    ),
    url(
        r'^comments/edit-update',
        comment_views.comments_edit_update,
        name='comments_edit_update_ajax'
    ),
    url(
        r'^donations/list',
        donation_views.get_donation_items,
        name='get_donation_items_ajax'
    ),
    url(
        r'^admincomments/(?P<content_type_model_name>[A-Za-z_\-]+)/('
        r'?P<object_id>['r'0-9]+)/$',
        comment_views.CommentList.as_view()
    ),
    url(
        r'^admincomments/(?P<pk>[0-9]+)/$',
        comment_views.CommentDetail.as_view()
    ),
    url(
        r'^winefaires/',
        ajax_winefaire_views.WineFaire.as_view(),
        name='wine_faire_ajax'
    ),
    url(
        r'^likes/(?P<content_type_model_name>[A-Za-z_\-]+)/('
        r'?P<object_id>['r'0-9]+)/$',
        like_views.LikeListView.as_view()
    )
]
