version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8002:8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./src/static:/static
    depends_on:
      - web

  ngrok:
    image: wernight/ngrok:latest
    links:
      - nginx
    command:
      - /bin/sh
      - -c
      - |
        ngrok start --all
    volumes:
      - .:/home/ngrok/.ngrok2/
    ports:
      - "4040:4040"

  db:
    image: "postgis/postgis:12-3.1"
    volumes:
      - ./docker/data/postgres_data:/var/lib/postgresql/data
      - ./docker/create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    restart: always
#    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=raisin
      - POSTGRES_DB=raisin

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "mkdir /project/src/logs ;  python3 src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/project/
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SETTINGS_MODULE=raisin.settings
    env_file:
      - raisin/.env_dev
    working_dir: "/project"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "mkdir /project/logs/ ;  export BROKER_URL='redis://redis:6379/0' && celery worker -b 'redis://redis:6379/0'  -B -l info -A my_celery.celery_app"
    volumes:
      - ../:/project
    environment:
      - PYTHONUNBUFFERED=0
      - DJANGO_SETTINGS_MODULE=raisin.settings
      - BROKER_URL='redis://redis:6379/0'
    env_file:
      - raisin/.env_dev
    working_dir: "/project/src/"
    depends_on:
      - db

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./docker/data/redis_data:/data
