# Generated by Django 2.0 on 2022-01-11 05:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=10)),
                ('geometry_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('geometry_multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('alt_names', models.ManyToManyField(to='cities.AlternativeName')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='urban_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cities.UrbanArea'),
        ),
    ]
