# Generated by Django 2.2.28 on 2022-05-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_auto_20220501_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='continent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='country',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='district',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='region',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Author'),
        ),
    ]
