# Generated by Django 2.2.28 on 2022-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_auto_20220501_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='region',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='alt_names',
            field=models.ManyToManyField(null=True, to='cities.AlternativeName'),
        ),
    ]
