# Generated by Django 2.2.28 on 2022-05-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_auto_20220502_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
