# Generated by Django 2.2.28 on 2022-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_auto_20220509_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
