# Generated by Django 2.2.28 on 2022-06-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20220614_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='urban_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='cities.UrbanArea'),
        ),
    ]
