# Generated by Django 3.2.13 on 2022-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_auto_20220621_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='continent',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='country',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='district',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='region',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subregion',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='osm_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
