# Generated by Django 3.2.13 on 2022-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0024_auto_20220704_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin_level',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15)], max_length=2),
        ),
    ]
