# Generated by Django 3.2.13 on 2022-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_city_admin_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
    ]
