# Generated by Django 3.2.13 on 2022-07-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0026_alter_district_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='osm_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
