# Generated by Django 3.2.13 on 2022-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0027_auto_20220709_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='admin_level',
            field=models.CharField(blank=True, choices=[('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15)], max_length=2),
        ),
    ]
