# Generated by Django 3.2.13 on 2022-09-30 05:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0028_alter_city_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=12),
        ),
        migrations.AddField(
            model_name='continent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='continent',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=2),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=5),
        ),
        migrations.AddField(
            model_name='district',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=14),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='zoom_scale',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='region',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=6),
        ),
        migrations.AddField(
            model_name='subregion',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='subregion',
            name='zoom_scale',
            field=models.IntegerField(choices=[], default=8),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='zoom_scale',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16)], default=1),
        ),
    ]
