# Generated by Django 3.2.13 on 2023-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0029_auto_20220930_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativename',
            options={'ordering': ['-is_preferred']},
        ),
        migrations.AddField(
            model_name='alternativename',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug_it',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='slug_ja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='alternativename',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_alternativename'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_city'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='continent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_continent'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_country'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_district'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='postalcode',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_postalcode'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_region'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_subregion'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug__isnull', False)), fields=('id', 'slug'), name='slug_uniq_urbanarea'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_en__isnull', False)), fields=('id', 'slug_en'), name='slug_en_uniq_urbanarea'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_ja__isnull', False)), fields=('id', 'slug_ja'), name='slug_js_uniq_urbanarea'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_fr__isnull', False)), fields=('id', 'slug_fr'), name='slug_fr_uniq_urbanarea'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_it__isnull', False)), fields=('id', 'slug_it'), name='slug_it_uniq_urbanarea'),
        ),
        migrations.AddConstraint(
            model_name='urbanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('slug_es__isnull', False)), fields=('id', 'slug_es'), name='slug_es_uniq_urbanarea'),
        ),
    ]
