# Generated by Django 3.2.13 on 2023-01-20 09:58

from django.db import migrations


def update_slugs(apps, schema_editor):
    continent_model = apps.get_model('cities', 'Continent')
    continents = continent_model.objects.all()
    for continent in continents:
        try:
            continent.save()
        except Exception as e:
            print(e)
    country_model = apps.get_model('cities', 'Country')
    countries = country_model.objects.all()
    for country in countries:
        try:
            country.save()
        except Exception as e:
            print(e)
    region_model = apps.get_model('cities', 'Region')
    regions = region_model.objects.all()
    for region in regions:
        try:
            region.save()
        except Exception as e:
            print(e)
    city_model = apps.get_model('cities', 'City')
    cities = city_model.objects.all()
    for city in cities:
        try:
            city.save()
        except Exception as e:
            print(e)
    district_model = apps.get_model('cities', 'District')
    districts = district_model.objects.all()
    for district in districts:
        try:
            district.save()
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0030_auto_20230120_0949'),
    ]

    operations = [
        migrations.RunPython(update_slugs)
    ]
