# Generated by Django 3.2.13 on 2023-01-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0031_auto_20230120_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='continent',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='district',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subregion',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='urbanarea',
            name='osm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
